# Generated by Django 3.1.1 on 2020-12-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaint", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="image",
            field=models.ImageField(
                blank=True,
                default="donation-pics/default.jpg",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
