# Generated by Django 3.1.1 on 2020-11-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcepost",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("RESERVED", "Reserved"),
                    ("PENDING", "Pending"),
                    ("CLOSED", "Closed"),
                ],
                default="Available",
                max_length=100,
            ),
        ),
    ]
