# Generated by Django 3.1.1 on 2020-10-14 06:49

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_location',
            field=places.fields.PlacesField(blank=True, default='', max_length=255, null=True),
        ),
    ]
