# Generated by Django 3.1.1 on 2020-10-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_auto_20201012_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepost',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='donation-pics'),
        ),
    ]
