# Generated by Django 3.1.1 on 2020-10-13 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20201012_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcepost',
            name='dropoff_time_1',
        ),
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_time_2',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_time_3',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resourcepost',
            name='image',
            field=models.ImageField(default='donation-pics/default.jpg', upload_to='donation-pics'),
        ),
        migrations.AlterField(
            model_name='resourcepost',
            name='resource_category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('MDCL', 'Medical/ PPE'), ('CLTH', 'Clothing/ Covers'), ('ELEC', 'Electronics'), ('OTHR', 'Others')], default='Food', max_length=100),
        ),
    ]
