# Generated by Django 3.1.1 on 2020-10-13 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_auto_20201012_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepost',
            name='dropoff_time_1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
