# Generated by Django 3.1.1 on 2020-10-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_resourcepost_dropoff_time_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepost',
            name='resource_category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('MDCL', 'Medical/ PPE'), ('CLTH', 'Clothing/ Covers'), ('ELEC', 'Electronics'), ('OTHR', 'Others')], max_length=100),
        ),
    ]
