# Generated by Django 3.1.1 on 2020-10-13 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_auto_20201013_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_time_2',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_time_3',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resourcepost',
            name='image',
            field=models.ImageField(blank=True, default='donation-pics/default.jpg', upload_to='donation-pics'),
        ),
    ]
