# Generated by Django 3.1.1 on 2020-10-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_auto_20201013_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_time_2',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_time_3',
            field=models.TimeField(blank=True),
        ),
    ]
