# Generated by Django 3.1.1 on 2020-10-13 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_auto_20201013_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_time_1',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
