# Generated by Django 3.1.1 on 2020-10-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_auto_20201013_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_time_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_time_3',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
