# Generated by Django 3.1.1 on 2020-10-14 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0011_auto_20201013_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_time_1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
