# Generated by Django 3.1.1 on 2020-10-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0012_auto_20201013_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_time_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcepost',
            name='dropoff_time_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
