# Generated by Django 3.1.2 on 2020-10-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helpseeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=128)),
                ('borough', models.CharField(choices=[('Manhattan', 'Manhattan'), ('Brooklyn', 'Brooklyn'), ('Queens', 'Queens'), ('The Bronx', 'The Bronx'), ('Staten Island', 'Staten Island')], max_length=13)),
                ('complaint_count', models.IntegerField(default=0)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('rc_1', models.CharField(blank=True, choices=[('FOOD', 'Food'), ('PPE', 'Personal Protective Equipment'), ('CLOTH', 'Clothing And Covers')], default=None, max_length=5, null=True)),
                ('rc_2', models.CharField(blank=True, choices=[('FOOD', 'Food'), ('PPE', 'Personal Protective Equipment'), ('CLOTH', 'Clothing And Covers')], default=None, max_length=5, null=True)),
                ('rc_3', models.CharField(blank=True, choices=[('FOOD', 'Food'), ('PPE', 'Personal Protective Equipment'), ('CLOTH', 'Clothing And Covers')], default=None, max_length=5, null=True)),
            ],
        ),
    ]
