# Generated by Django 3.1.3 on 2020-11-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpseekerprofile",
            name="rc_1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FOOD", "Food"),
                    ("MEDICAL/ PPE", "Medical/ PPE"),
                    ("CLOTHING/ COVERS", "Clothing/ Covers"),
                    ("ELECTRONICS", "Electronics"),
                    ("OTHERS", "Others"),
                ],
                default=None,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="helpseekerprofile",
            name="rc_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FOOD", "Food"),
                    ("MEDICAL/ PPE", "Medical/ PPE"),
                    ("CLOTHING/ COVERS", "Clothing/ Covers"),
                    ("ELECTRONICS", "Electronics"),
                    ("OTHERS", "Others"),
                ],
                default=None,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="helpseekerprofile",
            name="rc_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FOOD", "Food"),
                    ("MEDICAL/ PPE", "Medical/ PPE"),
                    ("CLOTHING/ COVERS", "Clothing/ Covers"),
                    ("ELECTRONICS", "Electronics"),
                    ("OTHERS", "Others"),
                ],
                default=None,
                max_length=16,
                null=True,
            ),
        ),
    ]
