# Generated by Django 3.1.1 on 2020-12-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_auto_20201130_1234"),
        ("register", "0002_auto_20201201_1442"),
    ]

    operations = []
