# Generated by Django 3.1.1 on 2020-10-29 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReservationPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dropoff_time_request",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2020, 10, 29, 3, 36, 56, 40342, tzinfo=utc
                        )
                    ),
                ),
            ],
        ),
    ]
