# Generated by Django 3.1.1 on 2020-10-29 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationpost',
            name='dropoff_time_request',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
