# Generated by Django 3.1.1 on 2020-12-01 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="date",
        ),
        migrations.AddField(
            model_name="notification",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
