# Generated by Django 3.1.1 on 2020-11-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservationpost_reservationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationpost',
            name='reservationstatus',
            field=models.IntegerField(choices=[(1, 'ACCEPT'), (2, 'REJECT'), (3, 'PENDING')], default=3),
        ),
    ]
