# Generated by Django 3.1.1 on 2020-11-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_reservationpost_reservationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationpost',
            name='reservationstatus',
            field=models.IntegerField(choices=[(1, 'accept'), (2, 'reject'), (3, 'pending')], default=3),
        ),
    ]
