# Generated by Django 3.1.1 on 2020-12-02 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_merge_20201201_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 18, 14, 34, 346254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservationpost',
            name='dropoff_time_request',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 18, 14, 34, 346254, tzinfo=utc)),
        ),
    ]
