# Generated by Django 3.1.1 on 2020-12-02 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20201202_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationpost',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservationpost',
            name='dropoff_time_request',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
